// Copyright 2020 Anthony F. Stuart - All rights reserved.
//
// This program and the accompanying materials are made available
// under the terms of the GNU General Public License. For other license
// options please contact the copyright owner.
//
// This program is made available on an "as is" basis, without
// warranties or conditions of any kind, either express or implied.

const char *ysw_instruments =
"Acoustic Grand Piano\n"
"Bright Acoustic Piano\n"
"Electric Grand Piano\n"
"Honky Tonk Piano\n"
"Electric Piano 1\n"
"Electric Piano 2\n"
"Harpsichord\n"
"Clavinet\n"
"Celesta\n"
"Glockenspiel\n"
"Music Box\n"
"Vibraphone\n"
"Marimba\n"
"Xylophone\n"
"Tubular Bells\n"
"Dulcimer\n"
"Drawbar Organ\n"
"Percussive Organ\n"
"Rock Organ\n"
"Church Organ\n"
"Reed Organ\n"
"Accordion\n"
"Harmonica\n"
"Tango Accordion\n"
"Acoustic Guitar Nylon\n"
"Acoustic Guitar Steel\n"
"Electric Guitar Jazz\n"
"Electric Guitar Clean\n"
"Electric Guitar Muted\n"
"Overdriven Guitar\n"
"Distortion Guitar\n"
"Guitar Harmonics\n"
"Acoustic Bass\n"
"Electric Bass Finger\n"
"Electric Bass Pick\n"
"Fretless Bass\n"
"Slap Bass 1\n"
"Slap Bass 2\n"
"Synth Bass 1\n"
"Synth Bass 2\n"
"Violin\n"
"Viola\n"
"Cello\n"
"Contrabass\n"
"Tremolo Strings\n"
"Pizzicato Strings\n"
"Orchestral Harp\n"
"Timpani\n"
"String Ensemble 1\n"
"String Ensemble 2\n"
"Synth Strings 1\n"
"Synth Strings 2\n"
"Choir Aahs\n"
"Voice Oohs\n"
"Synth Choir\n"
"Orchestra Hit\n"
"Trumpet\n"
"Trombone\n"
"Tuba\n"
"Muted Trumpet\n"
"French Horn\n"
"Brass Section\n"
"Synth Brass 1\n"
"Synth Brass 2\n"
"Soprano Sax\n"
"Alto Sax\n"
"Tenor Sax\n"
"Baritone Sax\n"
"Oboe\n"
"English Horn\n"
"Bassoon\n"
"Clarinet\n"
"Piccolo\n"
"Flute\n"
"Recorder\n"
"Pan Flute\n"
"Blown Bottle\n"
"Shakuhachi\n"
"Whistle\n"
"Ocarina\n"
"Lead 1 Square\n"
"Lead 2 Sawtooth\n"
"Lead 3 Calliope\n"
"Lead 4 Chiff\n"
"Lead 5 Charang\n"
"Lead 6 Voice\n"
"Lead 7 Fifths\n"
"Lead 8 Bass + Lead\n"
"Pad 1 New Age\n"
"Pad 2 Warm\n"
"Pad 3 Polysynth\n"
"Pad 4 Choir\n"
"Pad 5 Bowed\n"
"Pad 6 Metallic\n"
"Pad 7 Halo\n"
"Pad 8 Sweep\n"
"Fx 1 Rain\n"
"Fx 2 Soundtrack\n"
"Fx 3 Crystal\n"
"Fx 4 Atmosphere\n"
"Fx 5 Brightness\n"
"Fx 6 Goblins\n"
"Fx 7 Echoes\n"
"Fx 8 Sci Fi\n"
"Sitar\n"
"Banjo\n"
"Shamisen\n"
"Koto\n"
"Kalimba\n"
"Bagpipe\n"
"Fiddle\n"
"Shanai\n"
"Tinkle Bell\n"
"Agogo\n"
"Steel Drums\n"
"Woodblock\n"
"Taiko Drum\n"
"Melodic Tom\n"
"Synth Drum\n"
"Reverse Cymbal\n"
"Guitar Fret Noise\n"
"Breath Noise\n"
"Seashore\n"
"Bird Tweet\n"
"Telephone Ring\n"
"Helicopter\n"
"Applause\n"
"Gunshot\n"
;

