// Copyright 2020 Anthony F. Stuart - All rights reserved.
//
// This program and the accompanying materials are made available
// under the terms of the GNU General Public License. For other license
// options please contact the copyright owner.
//
// This program is made available on an "as is" basis, without
// warranties or conditions of any kind, either express or implied.

#if defined(MM_VERSION) && MM_VERSION == MM_V02

#include "ysw_editor.h"
#include "ysw_a2dp_source.h"
#include "ysw_app.h"
#include "ysw_bt_synth.h"
#include "ysw_common.h"
#include "ysw_event.h"
#include "ysw_fluid_synth.h"
#include "ysw_heap.h"
#include "ysw_i2s.h"
#include "ysw_remote.h"
#include "ysw_keyboard.h"
#include "ysw_led.h"
#include "ysw_mapper.h"
#include "ysw_midi.h"
#include "ysw_mod_synth.h"
#include "ysw_sequencer.h"
#include "ysw_staff.h"
#include "ysw_spiffs.h"
#include "ysw_touch.h"
#include "ysw_tty.h"
#include "ysw_vs_synth.h"
#include "zm_music.h"
#include "eli_ili9341_xpt2046.h"
#include "lvgl/lvgl.h"
#include "driver/gpio.h"
#include "driver/dac.h"
#include "driver/i2c.h"
#include "driver/i2s.h"
#include "driver/spi_master.h"
#include "esp_log.h"
#include "stdlib.h"

#define TAG "YSW_MMV02"

#define WT_SYNTH 1
#define VS_SYNTH 2
#define BT_SYNTH 3
#define FLUID_SYNTH 4
#define MOD_SYNTH 5

#define SYNTH_TYPE MOD_SYNTH

// Layout of keycodes generated by keyboard:
//
//    0,  1,      2,  3,  4,      5,  6,  7,  8,
//  9, 10, 11, 12, 13, 14, 15,   16, 17, 18, 19,
//   20, 21,     22, 23, 24,     25, 26, 27, 28,
// 29, 30, 31, 32, 33, 34, 35,   36, 37, 38, 39,

static const ysw_mapper_item_t mmv02_map[] = {
    /*  0 */ -73,
    /*  1 */ -75,
    /*  2 */ -78,
    /*  3 */ -80,
    /*  4 */ -82,
    /*  5 */ YSW_R1_C1,
    /*  6 */ YSW_R1_C2,
    /*  7 */ YSW_R1_C3,
    /*  8 */ YSW_R1_C4,
    /*  9 */ -72,
    /* 10 */ -74,
    /* 11 */ -76,
    /* 12 */ -77,
    /* 13 */ -79,
    /* 14 */ -81,
    /* 15 */ -83,
    /* 16 */ YSW_R2_C1,
    /* 17 */ YSW_R2_C2,
    /* 18 */ YSW_R2_C3,
    /* 19 */ YSW_R2_C4,
    /* 20 */ -61,
    /* 21 */ -63,
    /* 22 */ -66,
    /* 23 */ -68,
    /* 24 */ -70,
    /* 25 */ YSW_R3_C1,
    /* 26 */ YSW_R3_C2,
    /* 27 */ YSW_R3_C3,
    /* 28 */ YSW_R3_C4,
    /* 29 */ -60,
    /* 30 */ -62,
    /* 31 */ -64,
    /* 32 */ -65,
    /* 33 */ -67,
    /* 34 */ -69,
    /* 35 */ -71,
    /* 36 */ YSW_R4_C1,
    /* 37 */ YSW_R4_C2,
    /* 38 */ YSW_R4_C3,
    /* 39 */ YSW_R4_C4,
};

ysw_mod_synth_t *ysw_mod_synth;

static int32_t generate_audio(uint8_t *buffer, int32_t bytes_requested)
{
    int32_t bytes_generated = 0;
    if (buffer && bytes_requested) {
        ysw_mod_generate_samples(ysw_mod_synth,
                (int16_t*)buffer, bytes_requested / 4, YSW_MOD_16BIT_UNSIGNED);
        bytes_generated = bytes_requested;
    }
    return bytes_generated;
}

static void initialize_audio_output(void)
{
#if SYNTH_TYPE == FLUID_SYNTH
    ysw_a2dp_source_initialize(generate_audio); // for bluetooth speaker
#elif SYNTH_TYPE == MOD_SYNTH
    // Enable I2S internal DAC on GPIO 25 with GPIO 26 in use for keyboard
    ESP_LOGD(TAG, "Enabling I2S internal DAC on GPIO 25 with GPIO 26 in use for keyboard");

    static const i2s_config_t i2s_config = {
        .mode = I2S_MODE_MASTER | I2S_MODE_TX | I2S_MODE_DAC_BUILT_IN,
        .sample_rate = YSW_I2S_SAMPLE_RATE,
        .bits_per_sample = 16,
        .channel_format = I2S_CHANNEL_FMT_RIGHT_LEFT,
        .communication_format = I2S_COMM_FORMAT_I2S_MSB,
        .intr_alloc_flags = 0,
        .dma_buf_count = YSW_I2S_BUFFER_COUNT,
        .dma_buf_len = YSW_I2S_SAMPLE_COUNT,
        .use_apll = false
    };

    $(i2s_driver_install(I2S_NUM_0, &i2s_config, 0, NULL));

    ESP_LOGD(TAG, "calling i2s_set_dac_mode(I2S_DAC_CHANNEL_RIGHT_EN)");
    $(i2s_set_dac_mode(I2S_DAC_CHANNEL_RIGHT_EN));
#endif
}

static void initialize_touch_screen(void)
{
    ESP_LOGD(TAG, "configuring Music Machine v02 touch screen");
    eli_ili9341_xpt2046_config_t new_config = {
        .mosi = 5,
        .clk = 18,
        .ili9341_cs = 0,
        .xpt2046_cs = 22,
        .dc = 2,
        .rst = -1,
        .bckl = -1,
        .miso = 19,
        .irq = 21,
        .x_min = 483,
        .y_min = 416,
        .x_max = 3829,
        .y_max = 3655,
        .is_invert_y = true,
        .spi_host = VSPI_HOST,
    };
    eli_ili9341_xpt2046_initialize(&new_config);
}

void ysw_main_init_device(ysw_bus_t *bus)
{
    initialize_touch_screen();

    ysw_led_config_t led_config = {
        .gpio = 4,
    };
    ysw_led_create_task(bus, &led_config);

    ysw_keyboard_config_t keyboard_config = {
        .rows = ysw_array_load(6, 33, 32, 35, 34, 39, 36),
        .columns = ysw_array_load(7, 15, 13, 12, 14, 27, 26, 23),
    };
    ysw_keyboard_create_task(bus, &keyboard_config);
    ysw_mapper_create_task(bus, mmv02_map);
}

void ysw_main_init_synthesizer(ysw_bus_t *bus, zm_music_t *music)
{
#if SYNTH_TYPE == BT_SYNTH
    ESP_LOGD(TAG, "configuring BlueTooth synth");
    ysw_bt_synth_create_task(bus);
#elif SYNTH_TYPE == FLUID_SYNTH
    ESP_LOGD(TAG, "configuring FluidSynth synth");
    ysw_fluid_synth_create_task(bus, YSW_MUSIC_SOUNDFONT, "a2dp");
#elif SYNTH_TYPE == MOD_SYNTH
    ysw_mod_synth = ysw_mod_synth_create_task(bus);
#endif
    ysw_i2s_create_task(initialize_audio_output, generate_audio);
}

#endif
