// Copyright 2020 Anthony F. Stuart - All rights reserved.
//
// This program and the accompanying materials are made available
// under the terms of the GNU General Public License. For other license
// options please contact the copyright owner.
//
// This program is made available on an "as is" basis, without
// warranties or conditions of any kind, either express or implied.


#include "ysw_editor.h"
#include "ysw_common.h"
#include "ysw_event.h"
#include "ysw_heap.h"
#include "ysw_task.h"
#include "zm_music.h"
#include "esp_log.h"
#include "assert.h"

#define TAG "INPUT"

// Layout of keycodes generated by keyboard:
//
//    0,  1,      2,  3,  4,      5,  6,  7,  8,
//  9, 10, 11, 12, 13, 14, 15,   16, 17, 18, 19,
//   20, 21,     22, 23, 24,     25, 26, 27, 28,
// 29, 30, 31, 32, 33, 34, 35,   36, 37, 38, 39,

// Mapping of keycodes to note values and keypad values:

static const uint8_t key_map[] = {
    /* 1 */   13, 15,     18, 20, 22,     24, 25, 26, 27,
    /* 2 */ 12, 14, 16, 17, 19, 21, 23,   28, 29, 30, 31,
    /* 3 */    1,  3,      6,  8, 10,     32, 33, 34, 35,
    /* 4 */  0,  2,  4,  5,  7,  9, 11,   36, 37, 38, 39,
};

#define KEY_MAP_SZ (sizeof(key_map) / sizeof(key_map[0]))

// 0 % 2 = 0
// 1 % 2 = 1 C
// 2 % 2 = 0
// 3 % 2 = 1 E
// 4 % 2 = 0 
// 5 % 2 = 1 G
// 6 % 2 = 0

// position / 2 >= count ? space-after-note : position % 2 ? note index / 2 : space-before-note

bool ysw_editor_is_space(zm_passage_t *passage, uint32_t position)
{
    return ((position / 2) >= ysw_array_get_count(passage->beats)) || (position % 2 == 0);
}

zm_beat_t *ysw_editor_get_beat(zm_passage_t *passage, uint32_t position)
{
    zm_beat_t *beat = NULL;
    uint32_t beat_index = position / 2;
    if ((beat_index < ysw_array_get_count(passage->beats)) && ((position % 2) == 1)) {
        beat = ysw_array_get(passage->beats, beat_index);
    }
    return beat;
}

int32_t ysw_editor_get_beat_index(zm_passage_t *passage, uint32_t position)
{
    int32_t beat_index = position / 2;
    if ((beat_index >= ysw_array_get_count(passage->beats)) || ((position % 2) == 0)) {
        beat_index = -1;
    }
    return beat_index;
}

typedef struct {
    ysw_bus_h bus;
    zm_passage_t *passage;
    uint32_t position;
    bool is_insert;
} context_t;

static void on_key_down(context_t *context, ysw_event_key_down_t *event)
{
    assert(event->key < KEY_MAP_SZ);
    uint8_t value = key_map[event->key];
    ESP_LOGD(TAG, "key=%d, value=%d", event->key, value);
    if (value < 24) {
        ysw_event_fire_note_on(context->bus, 0, 60 + value, 80);
    }
}

static void on_key_up(context_t *context, ysw_event_key_up_t *event)
{
    assert(event->key < KEY_MAP_SZ);
    uint8_t value = key_map[event->key];
    if (value < 24) {
        ysw_event_fire_note_off(context->bus, 0, 60 + value);
    }
}

static void on_key_pressed(context_t *context, ysw_event_key_pressed_t *event)
{
    assert(event->key < KEY_MAP_SZ);
    uint8_t value = key_map[event->key];
    ESP_LOGD(TAG, "key=%d, value=%d", event->key, value);
    if (value < 24) {
        int32_t beat_index = context->position / 2;
        if (context->position % 2 == 0) {
            zm_beat_t *beat = ysw_heap_allocate(sizeof(zm_beat_t));
            beat->tone.note = 60 + value;
            ysw_array_insert(context->passage->beats, beat_index, beat);
            if (context->is_insert) {
                context->position += 2; // move from space to next space
            } else {
                context->position += 1; // move from space to note
            }
        } else {
            zm_beat_t *beat = ysw_array_get(context->passage->beats, beat_index);
            beat->tone.note = 60 + value;
            if (context->is_insert) {
                context->position += 1;
            }
        }
    } else if (value == 35) {
        if (context->position > 0) {
            context->position--;
        }
    } else if (value == 39) {
        if (context->position < (ysw_array_get_count(context->passage->beats) * 2)) {
            context->position++;
        }
    } else {
        return;
    }
    ysw_event_passage_update_t passage_update = {
        .passage = context->passage,
        .position = context->position,
    };
    ysw_event_fire_passage_update(context->bus, &passage_update);
}

static void process_event(void *caller_context, ysw_event_t *event)
{
    context_t *context = caller_context;
    switch (event->header.type) {
        case YSW_EVENT_KEY_DOWN:
            on_key_down(context, &event->key_down);
            break;
        case YSW_EVENT_KEY_UP:
            on_key_up(context, &event->key_up);
            break;
        case YSW_EVENT_KEY_PRESSED:
            on_key_pressed(context, &event->key_pressed);
            break;
        default:
            break;
    }
}

void ysw_editor_create_task(ysw_bus_h bus)
{
    context_t *context = ysw_heap_allocate(sizeof(context_t));

    context->bus = bus;
    context->passage = ysw_heap_allocate(sizeof(zm_passage_t));
    context->passage->beats = ysw_array_create(64);
    context->position = 0;
    context->is_insert = true;

    ysw_task_config_t config = ysw_task_default_config;

    config.name = TAG;
    config.bus = bus;
    config.event_handler = process_event;
    config.caller_context = context;

    ysw_task_h task = ysw_task_create(&config);
    ysw_task_subscribe(task, YSW_ORIGIN_KEYBOARD);
}
